# Vagrant configuration for generic/ubuntu Xenial (16.04)

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1604"
  config.ssh.username = "vagrant"
  config.ssh.insert_key = false

  config.vm.define :hlfv12 do |v| 	  
    #config.vm.provider "hyperv"
    #config.vm.network "public_network"
	  #config.vm.synced_folder ".", "/vagrant", disabled: true
	  #config.vm.synced_folder ".", "/vagrant", type: "smb"
    #config.vm.synced_folder ".", "/vagrant", create: true, mount_options: ["vers=3.0"]
    config.vm.synced_folder ".", "/vagrant"

    #config.vm.post_up_message = "Execute: cd ~/fabric-dev-servers && export FABRIC_VERSION=hlfv12 && ./startFabric.sh && ./createPeerAdminCard.sh && composer-playground"
    config.vm.post_up_message = "Execute: vagrant ssh -- -L 8080:localhost:8080"

    # If using Hyper-V
    config.vm.provider "hyperv" do |h, override|
      h.cpus = 2
      h.memory = 512
      h.maxmemory = 1024
      h.enable_virtualization_extensions = true
      h.linked_clone = true
      override.vm.network "public_network"
	  end

    # If using Virtualbox
	  config.vm.provider :virtualbox do |v, override|		
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ['modifyvm', :id, '--memory', '512']    		
      v.gui = false
      override.vm.network "private_network", type: "dhcp"
    end

    config.vm.provision "prereqs-ubuntu", type: "shell", path: "prereqs-ubuntu.sh", privileged: false
	  config.vm.provision "install_composer", type: "shell", path: "install_composer.sh", privileged: false

    config.vm.network "forwarded_port", guest: 8080, host: 8080
  end
end